
    subroutine ini
    use the_whole_varibles
    implicit none
    integer:: I_r,I_z,i1,i2
    real*8  r_resonance,z_resonance,b0_set
    real*8  total_cycles,tau_ion_predicted
    call start_ftime

    !-----------------------discharge set-------------------------------!
    iswitch_display= 1 ; !1--the running state display on screen; 0--write into a dat file
    iswitch_mcc=1  !0-monte carlo collsion off, 1-on  !energy conservation

    !iswitch_dielectric= 1: Cold plasma dispersion relationship, include ion current Ji and electron current Je in FDFD;
    !                    2: Cold plasma dispersion relationship, include electron current Je (wtihout Ji) in FDFD;
    !                    3: ion kinetics and electron cold: hot plasma dispersion (kenetic) relationship.
    !                    4: ion and electron kinetics: hot plasma dispersion (kenetic) relationship.
    iswitch_dielectric=  1 !only iswitch_dielectric=  1 and 2 has been tested.

    !iswitch_antenna_type= 0, single loop
    !                    =-1, left helical
    !                    = 1, right helical
    !                    = 2, half loop
    !                    = 3, Nagoya type-III
    iswitch_antenna_type = 0

    !important: this version only tests i_switch_power_mode=0. !!!
    i_switch_power_mode=1; !1:set constant total power; 0: set constant current Irf
    irf_set=1000;          !A    use when i_switch_power_mode=0;
    power=10e3;           !W    use when i_switch_power_mode=1;
    resistance=0.1         !ohm, antenna resistance,   use when i_switch_power_mode=1;

    iswitch_RF2=  0        !0 - swtich off RF2 (only 13.56 MHz); 1 - swtich on 2 MHz.
    irf2_set=2.*irf_set;         !A    use when i_switch_power_mode=0;


    !i_switch_B0=1: uniform b0_ci you specificly set;
    !           =2: load B0 from txt files;
    !           =3: B0 field generated by coils (subroutine background_b0)
    i_switch_B0= 3 ;
    b0_set=1;             !T. Note: used only when i_switch_B0=1, i.e., i_switch_B0=2 or 3--not use;

    i_switch_MHD_Te=1;    !1-te_in_FDFD evolution by MHD; 0-te_in_FDFD evolution only by MCC; 2-constant te_in_FDFD
    Te_set=10;            !eV. Note: use only when i_switch_MHD_Te=2

    max_density_set=1e19  !m-3, maxium initial plasma density
    ti_ini=10;            !eV , initial teamperature of ion
    te_ini=10;            !eV
    vz0=0.;               !m/s, Ion orientation speed

    n_pic=10              !total number of picture to record, i.e. record data at every td/n_pic
    td=5.e-3;             !s
    t_power_on=dt*2
    t_power_end=td*1.1
    dt_trf=5e-3;           !when setting dt_trf=0, set dt according to tau_ion_predicted; others, use the value
    tau_ion_predicted=1e-2 !s, Predicted energy constraint time, or an typical ion existing time, used to find dt only when dt_trf=0.
    dt_run_fdfd=20*trf
    t_rec_evolution=1*trf !trf
    t_rec_trajectory=trf/1!trf
    pn=1.0                !Pa, for calculation of v_in and v_en (collision frequency)

    call fdfd_ini
    call grid
    
    r_inject_cener=0.0;    !m, rc, central axial position of inject particle    
    z_inject_cener=0.0;    !m, zc, central axial position of inject particle   
    width_ne_r=0.025       !m, rw
    width_ne_z=0.4         !m, zw
    width_ne_source_r=width_ne_r
    width_ne_source_z=0.1
    r_resonance=r_inject_cener !m, radial resonant position,usually set r_resonance=r_inject_cener
    z_resonance=za            !m,  axial resonant position,usually set z_resonance=za
    
    call antenna
    call set_ne_Te_ini
    call mcc_constant
    
    if(i_switch_B0==2)then
        call load_B0
    elseif(i_switch_B0==3)then
        call background_b0
    else
        b0_DC(:,:,1)=0.
        b0_DC(:,:,2)=0.0D0
        b0_DC(:,:,3)=b0_set;
        b0_DC(:,:,4)=b0_set;
    endif
    B_resonance=2*pi*frequency/q_mass_i_spe(1)

    I_r=minloc(abs(r_resonance-r),1);
    I_z=minloc(abs(z_resonance-z),1);
    if(i_switch_B0==1)then
        B0_correction_factor=0.
    else
        B0_correction_factor=B_resonance/b0_DC(I_r,I_z,4)*1.0
        b0_DC=b0_DC*B0_correction_factor
    endif
    bz_max=maxval(b0_DC(1:2,1:nz,4))
    
    
    !find frequency2
    i1=1;i2=nz/2;
    I_z=maxloc(b0_DC(2,i1:i2,4),1);
    frequency2=q_mass_i_spe(1)*b0_DC(2,I_z+1,4)/(2*pi)

    te_ave=te_ini
    ti_ave =ti_ini
    te_2D=te_ini
    te_mhd=te_ini
    om=2*pi*frequency;
    omc2=(om/c)*(om/c)
    iom=i*om*mu0
    
    if(i_switch_power_mode==0)then
        i_now=irf_set
    else
        irf_set=sqrt(power/resistance);
        i_now=irf_set;
    endif

    power_Joule=i_now**2*resistance;  ! W
    nn=3.22e16*pn/133.322*cm3;        ! m-3
    
    if(tau_ion_predicted>td)tau_ion_predicted=td !when tau_ion>td, use td
    total_cycles=tau_ion_predicted/trf
    if(dt_trf<1e-10)then
        !set dt (Trf), according to the nature of energy conservation (loss <1%) in the RK4 format
        if(total_cycles<50)then
            dt_trf=5e-2
        elseif(total_cycles<1200)then
            dt_trf=2.5e-2
        elseif(total_cycles<1.5e5)then
            dt_trf=1e-2
        elseif(total_cycles<1.5e6)then
            dt_trf=5e-3
        else
            dt_trf=2.5e-3
        endif
    endif
    
    dt=dt_trf*trf;    
    
    vi_ex=sqrt(qe_abs*ti_ini/mi_spe(n_species));     !expectation of vi :  average speed
    ve_ex=sqrt(qe_abs*te_ini/me);     !expectation of ve :  average speed
    ek_ion_2D=ti_ini*1.5
    ek_ion_2D_r=ek_ion_2D/1.5
    t_rec_profiles=td/real(n_pic)

    if (n_species==1)then
        np_spe=1
    else
        do i_s=1,n_species-1
            if(i_s==1)then
                i1=1
                i2=ratio_species(i_s)*np_max
            else
                i1=i2+1
                i2=i1+ratio_species(i_s)*np_max-1
            endif
            np_spe(i1:i2)=i_s
        enddo
        np_spe(i2+1:np_max)=n_species
    endif


    call rec_para
    open (unit=42,file='1time_average.dat',status='unknown',iostat=ierror)
    open (unit=43,file='1time_trajectory.dat',status='unknown',iostat=ierror)
    end subroutine ini



    subroutine rec_para
    use the_whole_varibles
    implicit none
    real*8:: para(1:40)=0
    para(1)=nr;para(2)=nz;para(3)=max_density_set;para(4)=density_ave;
    para(5)=rs;para(6)=dr;para(7)=rl;para(8)=zs;para(9)=dz;para(10)=zl;
    para(11)=dt;para(12)=td;para(13)=pn; para(14)=i_now;para(15)=power_Joule;para(16)=bz_max;para(17)=B0_correction_factor
    para(18)=i_switch_B0; para(19)=t_rec_evolution; para(20)=np_max;

    para(21)=iswitch_RF2;para(23)=dt;para(24)=td;para(25)=trf;
    para(26)=n_species;para(29)=za;para(30)=ra;
    para(31)=z_inject_cener;para(32)=vi_ex;para(33)=ve_ex;para(34)=B_resonance
    para(35)=mp;para(36)=me;para(37)=n_macro;para(38)=power;para(39)=m_end;para(40)=rp

502 format(e12.4,' ')
    open (unit=75,file='1parameter.dat',status='unknown',iostat=ierror)
    write (75,502)para
    close(75)
    endsubroutine rec_para



    subroutine set_ne_Te_ini
    use the_whole_varibles
    implicit none
    real*8  :: ni_int,volume,ni_bd
    real*8  :: sr(1:nr),sz(1:nz),sr_half(2:nr),sz_half(2:nz)

    ni_bd=1e17; !m-3
    !set initial plasma
    ! Gaussian distribution: ni(r,z)=n0*exp(-r^2/(2*rw^2))*exp(-(z-zc)^2/(2*zw^2))
    ni=1e7; !initial set to avoid null value
    do ir=1,nr
        do iz=1,nz
            !if(i_plasma_region(ir,iz)>0.5)then
            tp1=exp(-(r(ir)-r_inject_cener)**2/(2*width_ne_r**2));
            tp2=exp(-(z(iz)-z_inject_cener)**2/(2*width_ne_z**2));
            ni(ir,iz)=ni_bd+max_density_set*(tp1*tp2);

            !exp distribution
            sr(ir)=1+max_density_set/ni_bd*tp1
            sz(iz)=1+max_density_set/ni_bd*tp2

            !!uniform source term
            !sr(ir)=1
            !sz(iz)=1
            !endif
        enddo
    enddo
    sr(1)=0;sr(nr)=0;
    sz(1)=0;sz(nz)=0;

    !ni=ni;
    te_in_FDFD=te_ini

    sr_half(2:nr)=0.5*(sr(1:nr-1)+sr(2:nr))
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    sr_half=sr_half/maxval(sr_half)
    sz_half=sz_half/maxval(sz_half)

    !PDF: density distribution probability
    ir=1;pdf_ne_r(ir)=0;
    ir=2;pdf_ne_r(ir)=pi*((dr*0.5)**2)*sr_half(ir)
    do ir=3,nr-1
        pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r2(ir)**2-r2(ir-1)**2)*sr_half(ir)
    enddo
    ir=nr;pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r(ir)**2-r2(ir-1)**2)*sr_half(ir)
    pdf_ne_r=pdf_ne_r/maxval(pdf_ne_r) !normalization
    do ir=1,nr
        if(abs(pdf_ne_r(ir)-1.)<1e-20)then
            pdf_ne_r(ir+1:nr)=2
            exit
        endif
    enddo

    iz=1;pdf_ne_z(iz)=0.
    iz=2;pdf_ne_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_z(iz)=pdf_ne_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_z(iz)=pdf_ne_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_z=pdf_ne_z/maxval(pdf_ne_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_z(iz)-1.)<1e-20)then
            pdf_ne_z(iz+1:nz)=2
            exit
        endif
    enddo

    !set plasma souce (inject with time)
    !plasma souce in z direction
    !set initial plasma
    ! Gaussian distribution: ni(r,z)=n0*exp(-r^2/(2*rw^2))*exp(-(z-zc)^2/(2*zw^2))
    !pdf_ne_source_r=pdf_ne_r

    do ir=1,nrp
        tp1=exp(-(r(ir)-r_inject_cener)**2/(2*width_ne_r**2)); !exp distribution
        sr(ir)=1+max_density_set/ni_bd*tp1
    enddo
    sr(1)=0;sr(nrp)=0;
    sr_half(2:nrp)=0.5*(sr(1:nrp-1)+sr(2:nrp))
    sr_half(2:nrp)=sr_half(2:nrp)/maxval(sr_half(2:nrp))

    !PDF: density distribution probability
    ir=1;pdf_ne_source_r(ir)=0;
    ir=2;pdf_ne_source_r(ir)=pi*((dr*0.5)**2)*sr_half(ir)
    do ir=3,nrp-1
        pdf_ne_source_r(ir)=pdf_ne_source_r(ir-1)+2*pi*(r2(ir)**2-r2(ir-1)**2)*sr_half(ir)
    enddo
    ir=nrp;pdf_ne_source_r(ir)=pdf_ne_source_r(ir-1)+2*pi*(r(ir)**2-r2(ir-1)**2)*sr_half(ir)
    pdf_ne_source_r=pdf_ne_source_r/maxval(pdf_ne_source_r) !normalization
    do ir=1,nrp
        if(abs(pdf_ne_source_r(ir)-1.)<1e-20)then
            pdf_ne_source_r(ir+1:nrp)=2
            exit
        endif
    enddo


    do iz=1,nz
        tp2=exp(-(z(iz)-z_inject_cener)**2/(2*width_ne_source_z**2));
        sz(iz)=1+max_density_set/ni_bd*tp2
    enddo
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    sz_half=sz_half/maxval(sz_half)

    iz=1;pdf_ne_source_z(iz)=0.
    iz=2;pdf_ne_source_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_source_z(iz)=pdf_ne_source_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_source_z(iz)=pdf_ne_source_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_source_z=pdf_ne_source_z/maxval(pdf_ne_source_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_source_z(iz)-1.)<1e-20)then
            pdf_ne_source_z(iz+1:nz)=2
            exit
        endif
    enddo

    !normalization
    ds=dr*dz
    ni_int=0.
    do iz=1,nz-1
        do ir=1,nrp-1
            ni_int=ni_int+2*pi/max_density_set*1./4.*(ni(ir,iz)*r(ir)+ni(ir+1,iz)*r(ir+1) &
                &               +ni(ir,iz+1)*r(ir)+ni(ir+1,iz+1)*r(ir+1))*ds
        end do
    end do

    volume=pi*rp**2*zl
    ni_ave_ratio=ni_int/volume
    n_macro=volume*ni_ave_ratio*max_density_set/np_max !n_macro=ni_int/np_max
    density_ave=ni_ave_ratio*max_density_set  !m-3

    endsubroutine set_ne_Te_ini




    subroutine set_ne_Te
    use the_whole_varibles
    implicit none

    ni=1e7;te_in_FDFD=0.2
    do ir=1,nr
        do iz=1,nz
            if(i_plasma_region(ir,iz)>0.5)then
                tp1=exp(-r(ir)**2/(2*width_ne_source_r**2));
                tp2=exp(-(z(iz)-z_inject_cener)**2/(2*width_ne_source_z**2));
                !if(density_2D(ir,iz)>1.)then
                ni(ir,iz)=n_macro*density_2D(ir,iz);        !the area the PIC module not simulate
                te_in_FDFD(ir,iz)=te_2D(ir,iz) !te_low_density*(1.+tp1*tp2)  !the area the PIC module not simulate
                !else
                !    ni(ir,iz)=max_density_set*(tp1*tp2); !m-3  !the area of overlap with the PIC module
                !    te_in_FDFD(ir,iz)=te_low_density*(1.+tp1*tp2)  !eV
                !endif
            endif
        enddo
    enddo
    endsubroutine set_ne_Te


    subroutine fdfd_ini
    use the_whole_varibles
    implicit none

    if(iswitch_antenna_type==0)then
        m_start=0
        m_end=-m_start
        m_delta=+2
    else
        m_start=-15
        m_end=-m_start
        m_delta=+1
    endif

    switch_plasma_vacuum_boundary=43 !switch boundary of plasma-vacuum rp; 0:nothing more; 1:tangent continuous ;2:tangent continuous + Div(E)=0(vacuum);
    !3 :tangent continuous + Div(E)=0 + Jpn=0
    !4 :tangent continuous + Div(E)=0 + pdv{Dn}{r}continuous
    !5 :tangent continuous + Div(E)=0 + Dn condinuous
    !7 :tangent continuous + Div(E)=0[outside] + Div(D)=0[inside]
    !8 :tangent continuous + B_th continuous
    !1X : only Ez continuous + X[don't use]
    !2X : X + Ez continuous
    !!!!!!!!!!!!!!!!!!!!!!!switch_plasma_vacuum_boundary �� ep û�в�ֵ!!!!!!!!!!!!!!!!!!!!!!
    switch_z_boundary=1 ! switch boundary condition of z=0/l; 1:conductor Boundary  ;  ; 3: z=0:conductor;z=zl:absorbing(For Vacuum Benchmark)
    switch_boundary_half_variables=1 !Switch how to handle variables on half Grid in boundaries.
    !0 : by eqs(inside) or extrapolation (outside);
    !1: Interpolation/Extrapolation to find it's quantity or derivative at boundary
    switch_r_0_boundary=1   !Switch how to handle the boundary condition of r=0. 1:old 2:new;
    switch_source_type=1 !0: z=0 Source(For Benchmark) 1:Antenna
    switch_divE=2!  0: ignore div(E) ; 1:not ignore div(E)(div(E) neq ===0); 2:ignore div(E) in Vacuum and nod ignore in Plasma Area
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!MUST NOT SET IT TO 0 (Except TESTing)
    endsubroutine fdfd_ini
